// the generated version number for CenterDot, filled in by CMake
#define CENTER_DOT_VERSION_MAJOR 1
#define CENTER_DOT_VERSION_MINOR 1
#define CENTER_DOT_VERSION_REVISION 0

#define CENTER_DOT_STRINGIFY_(x) #x
#define CENTER_DOT_STRINGIFY(x) CENTER_DOT_STRINGIFY_(x)

#define CENTER_DOT_VERSION_STRING          \
    CENTER_DOT_STRINGIFY(CENTER_DOT_VERSION_MAJOR) "." \
    CENTER_DOT_STRINGIFY(CENTER_DOT_VERSION_MINOR) "." \
    CENTER_DOT_STRINGIFY(CENTER_DOT_VERSION_REVISION)
